version: '3'

services:
  db:
    image: postgres:16.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - "./.env"

  web:
    restart: always
    build: .
    env_file:
    - .env
    # command: gunicorn --certfile=./infra/certs/cert.pem --keyfile=./infra/certs/key.pem config.wsgi --bind 0.0.0.0:8000
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    # expose:
    #   - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  # jenkins:
  #   image: jenkins/jenkins:lts
  #   ports:
  #     - 8080:8080
  #     - 50000:50000


  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./certs:/etc/nginx/certs

  # redis:
  #   image: redis:alpine

  # celery:
  #   build: .
  #   command: "celery -A config worker -l info"
  #   depends_on:
  #     - web
  #     - redis
  #     - db
  #   restart: always

  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - 5672:5672
