version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    restart: always
    build: .
    env_file:
    - .env
    # command: gunicorn --certfile=./certs/cert.pem --keyfile=./certs/key.pem config.wsgi --bind 0.0.0.0:8000
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    # expose:
    #   - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./certs:/etc/nginx/certs

  # redis:
  #   image: redis:alpine

  # celery:
  #   build: .
  #   command: "celery -A config worker -l info"
  #   depends_on:
  #     - web
  #     - redis
  #     - db
  #   restart: always

  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - 5672:5672

volumes:
  postgres_data:
