version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            pip install pytest
            pytest
  push-image:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create and push image in Docker Hub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker build -t cocorico84/personal_site .
            docker push cocorico84/personal_site
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
    - checkout
    - run:
        name: Deploy to Pythonanywhere
        command: |
            ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST "cd personal_site; git pull";

workflows:
  sample:
    jobs:
      - build-and-test
      - push-image:
          requires:
            - build-and-test
      - deploy:
          requires:
            - push-image

